# name: NYC Day Care
pygments: true
baseurl: /NYCdaycare

markdown: redcarpet

title_tag_text: NYC Day Care Map
h1_tag_text:  NYC Day Care Map

exclude: ["Procfile", "README.md", "CNAME"]

auto: true

# exclude: ["Gruntfile.js", "package.json", "node_modules"]
