# name: NYC Day Care
pygments: true
baseurl: /NYCdaycare

markdown: redcarpet
pygments: true

title_tag_text: Daycare Map NYC
h1_tag_text: Daycare Map NYC

exclude: ["Procfile", "README.md", "CNAME"]

auto: true

# exclude: ["Gruntfile.js", "package.json", "node_modules"]
